### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by waghanza** [rcrowley/mustache.sh#4]
Hi,

I have an SQL query computed by [pystach](https://github.com/defunkt/pystache) on a python3 app.

The is comments on this sql query (not SQL commentn, but pystache comments))

```
{{ ! my wonderful comment }}
```

When I use **mustache.sh**, `mustache.sh < query.sql`  my comment is

``` sh
$ ! my wonderful comment
```

**Comment by rcrowley** [comment]
The parser requires that the tag type directly follow the braces so your syntax needs to be `{{! my wonderful comment }}`.
